apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: grupo-4
    grupo: grupo-4
    product: diplomado
    tierApp: Backend
    app: devopsg4-app
    tier: backend
    type: service
  name: devopsg4-app
  namespace: grupo4
spec:
  selector:
    matchLabels:
      app:
        devopsg4-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate  
  template:
    metadata:
      labels:
        app: devopsg4-app
    spec:
      containers:
      - name: devopsg4-app
        image: luismellareyes/devopsg4
        ports:
        - containerPort: 80
        resources:
 #       livenessProbe:
 #         httpGet:
 #           path: /rest/msdxc/dxc
 #           port: 8084
 #         initialDelaySeconds: 3
 #         periodSeconds: 3
 #       readinessProbe:
 #         httpGet:
 #           path: /rest/msdxc/dxc
 #           port: 8084
 #         initialDelaySeconds: 3
 #         periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
   name: devopsg4-app-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8084
      protocol: TCP
  selector:
    app: devopsg4-app
    tier: backend
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devopsg4-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devopsg4-app
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopsg4-app-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /grupo4
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8084
