apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
  labels:
    app: simple-web
spec:
  selector:
    app: simple-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


