apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-deployment
  labels:
    app: simple-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - env:
        - name: ENV_VAR
          value: "KUBERNETES_USACH_TEST"
        envFrom:
        - configMapRef:
            name: configmap-env
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        name: simple-web
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/python"
            name: hostpath
      volumes:
        - name: hostpath
          emptyDir: {}
        - name: configmap-env
          configMap:
            name: configmap-env